remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Christopher Capps
description: Portfolio Site for Software Engineer Christopher Capps
lang: en-US
show_downloads: false
google_analytics: G-G3V2DWQJQR
year: 2023